
interactive: False
container_name: mytest
run_dir: /nfshome/lahaye/test_rundir
image_name: cpsc392_server_test
image_version: latest
num_runs: 10
num_gpus: 7
entrypoint: "/app/rundir/code/test2.py"

